// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfeUDy3cbRajkyVJHx3wnPZfOYpwRwoKU',
    appId: '1:915430780308:ios:bec7838f112c8abf12b381',
    messagingSenderId: '915430780308',
    projectId: 'e-commerce-pt-kinarya',
    storageBucket: 'e-commerce-pt-kinarya.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfeUDy3cbRajkyVJHx3wnPZfOYpwRwoKU',
    appId: '1:915430780308:ios:bec7838f112c8abf12b381',
    messagingSenderId: '915430780308',
    projectId: 'e-commerce-pt-kinarya',
    storageBucket: 'e-commerce-pt-kinarya.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBszGWCK0PsEd2IOKz0l1JTxfsvHpM9Kac',
    appId: '1:915430780308:web:cc764b8eed5615da12b381',
    messagingSenderId: '915430780308',
    projectId: 'e-commerce-pt-kinarya',
    authDomain: 'e-commerce-pt-kinarya.firebaseapp.com',
    storageBucket: 'e-commerce-pt-kinarya.firebasestorage.app',
    measurementId: 'G-54ZBVGNVYT',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBszGWCK0PsEd2IOKz0l1JTxfsvHpM9Kac',
    appId: '1:915430780308:web:cc764b8eed5615da12b381',
    messagingSenderId: '915430780308',
    projectId: 'e-commerce-pt-kinarya',
    authDomain: 'e-commerce-pt-kinarya.firebaseapp.com',
    storageBucket: 'e-commerce-pt-kinarya.firebasestorage.app',
    measurementId: 'G-54ZBVGNVYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJ1ACDiYs8oheSYLjCaknqIytb2jE8gk',
    appId: '1:915430780308:android:87c588ad9617be0612b381',
    messagingSenderId: '915430780308',
    projectId: 'e-commerce-pt-kinarya',
    storageBucket: 'e-commerce-pt-kinarya.firebasestorage.app',
  );

}